from ..base_devices import BaseDeviceV2
from ..fields import (
    FieldName,
    UIntField,
    SIntField,
    SInt32Field,
    DecimalField,
    SwapStringField,
    SerialNumberField,
    VersionField,
    SwitchField,
    BoolField,
    WriteableUIntField,
)


class EP2000(BaseDeviceV2):
    def __init__(self):
        super().__init__(
            [
                # These are plain 16-bit fields, not 32-bit - treating them
                # as 32-bit previously produced nonsensical values in the
                # tens of millions.
                SIntField(FieldName.CONSUMPTION_POWER_ALL, 142),
                UIntField(FieldName.PV_INPUT_POWER_ALL, 144),
                SIntField(FieldName.GRID_POWER_ALL, 146),
                DecimalField(FieldName.TOTAL_AC_CONSUMPTION, 152, 1),
                DecimalField(FieldName.TOTAL_GRID_FEED, 158, 1),
                SInt32Field(FieldName.TOTAL_PV_POWER, 1200),
                SInt32Field(FieldName.POWER_GENERATION, 1202, 0.1),
                UIntField(FieldName.PV_S1_POWER, 1212),
                DecimalField(FieldName.PV_S1_VOLTAGE, 1213, 1),
                DecimalField(FieldName.PV_S1_CURRENT, 1214, 1),
                UIntField(FieldName.PV_S2_POWER, 1220),
                DecimalField(FieldName.PV_S2_VOLTAGE, 1221, 1),
                DecimalField(FieldName.PV_S2_CURRENT, 1222, 1),
                UIntField(FieldName.PV_S3_POWER, 1228),
                DecimalField(FieldName.PV_S3_VOLTAGE, 1229, 1),
                DecimalField(FieldName.PV_S3_CURRENT, 1230, 1),
                UIntField(FieldName.PV_S4_POWER, 1236),
                DecimalField(FieldName.PV_S4_VOLTAGE, 1237, 1),
                DecimalField(FieldName.PV_S4_CURRENT, 1238, 1),
                UIntField(FieldName.PV_S5_POWER, 1244),
                DecimalField(FieldName.PV_S5_VOLTAGE, 1245, 1),
                DecimalField(FieldName.PV_S5_CURRENT, 1246, 1),
                DecimalField(FieldName.GRID_FREQUENCY, 1300, 1),
                SIntField(FieldName.TOTAL_AC_POWER, 1301),
                SIntField(FieldName.GRID_P1_POWER, 1313),
                DecimalField(FieldName.GRID_P1_VOLTAGE, 1314, 1),
                DecimalField(FieldName.GRID_P1_CURRENT, 1315, 1),
                SIntField(FieldName.GRID_P2_POWER, 1319),
                DecimalField(FieldName.GRID_P2_VOLTAGE, 1320, 1),
                DecimalField(FieldName.GRID_P2_CURRENT, 1321, 1),
                SIntField(FieldName.GRID_P3_POWER, 1325),
                DecimalField(FieldName.GRID_P3_VOLTAGE, 1326, 1),
                DecimalField(FieldName.GRID_P3_CURRENT, 1327, 1),
                UIntField(FieldName.TOTAL_SELF_CONSUMPTION, 1290),
                DecimalField(FieldName.AC_OUTPUT_FREQUENCY, 1500, 1),
                SIntField(FieldName.AC_P1_POWER, 1510),
                DecimalField(FieldName.AC_P1_VOLTAGE, 1511, 1),
                DecimalField(FieldName.AC_P1_CURRENT, 1512, 1),
                SIntField(FieldName.AC_P2_POWER, 1517),
                DecimalField(FieldName.AC_P2_VOLTAGE, 1518, 1),
                DecimalField(FieldName.AC_P2_CURRENT, 1519, 1),
                SIntField(FieldName.AC_P3_POWER, 1524),
                DecimalField(FieldName.AC_P3_VOLTAGE, 1525, 1),
                DecimalField(FieldName.AC_P3_CURRENT, 1526, 1),
                UIntField(FieldName.LOAD_P1_POWER, 1430),
                UIntField(FieldName.LOAD_P2_POWER, 1436),
                UIntField(FieldName.LOAD_P3_POWER, 1442),
                SwitchField(FieldName.CTRL_AC, 2011),
                UIntField(FieldName.BATTERY_SOC_RANGE_START, 2022),
                UIntField(FieldName.BATTERY_SOC_RANGE_END, 2023),
                SwitchField(FieldName.CHARGE_FROM_GRID_ENABLED, 2207),
                SwitchField(FieldName.GRID_EXPORT_ENABLED, 2208),
                WriteableUIntField(FieldName.MAX_GRID_EXPORT_POWER, 2215, min=0, max=6666),
                BoolField(FieldName.CTRL_GENERATOR, 2246),
                DecimalField(FieldName.GRID_VOLT_MIN_VAL, 2435, 1),
                DecimalField(FieldName.GRID_VOLT_MAX_VAL, 2436, 1),
                DecimalField(FieldName.GRID_FREQ_MIN_VALUE, 2437, 2),
                DecimalField(FieldName.GRID_FREQ_MAX_VALUE, 2438, 2),
                SwapStringField(FieldName.WIFI_NAME, 12002, 16),
                # Read directly here rather than via the pack_fields/
                # max_packs mechanism below, which is dormant (max_packs=0)
                # and untested for multi-pack selection.
                SwapStringField(FieldName.BMS_CONTROLLER_MODEL, 6101, 6),
                DecimalField(FieldName.PACK_VOLTAGE, 6111, 1),
                UIntField(FieldName.PACK_BATTERY_SOC, 6113, min=0, max=100),
                UIntField(FieldName.PACK_SOH, 6114, min=0, max=100),
                UIntField(FieldName.ACTIVE_CELL_COUNT, 6153),
                UIntField(FieldName.BATTERY_STACK_COUNT, 6154),
                # Exploratory, unverified: "Total Node Count", documented
                # alongside a separate write-only discovery-trigger register.
                UIntField(FieldName.TOTAL_NODE_COUNT, 21001),
            ],
            [
                SwapStringField(FieldName.PACK_TYPE, 6101, 6),
                SerialNumberField(FieldName.PACK_SN, 6107),
                VersionField(FieldName.PACK_VER_BCU, 6175),
                VersionField(FieldName.PACK_VER_BMU, 6178),
                VersionField(FieldName.PACK_VER_SAFETY_MOD, 6181),
                VersionField(FieldName.PACK_VER_HV_MOD, 6184),
            ],
            # max_packs=2,
        )
